name: Snyk scheduled test
on:
  schedule:
    - cron: '0 2 * * 1'
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      REPORT_FILE: test.json
    steps:
      - uses: actions/checkout@3

      - uses: snyk/actions/setup@master

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --org=radar-base --configuration-matching='^releaseRuntimeClasspath$' --exclude=radar-android-empatica --json-file-output=${{ env.REPORT_FILE }}

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        with:
          report-file: ${{ env.REPORT_FILE }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() }}
