name: Snyk scheduled test
on:
  schedule:
    - cron: '0 2 * * 1'
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      REPORT_FILE: test.json
    steps:
      - uses: actions/checkout@3

      - uses: snyk/actions/setup@master
        with:
          snyk-version: 1.931.0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Decrypt libraries
        run: ./.github/scripts/decrypt_libraries.sh
        env:
          E4LINK_PASSPHRASE: ${{ secrets.E4LINK_PASSPHRASE }}

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-sub-projects --org=radar-base --configuration-matching='^releaseRuntimeClasspath$' --json-file-output=${{ env.REPORT_FILE }}

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        with:
          report-file: ${{ env.REPORT_FILE }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() }}
