name: Snyk test
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [master]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --org=radar-base  --fail-on=upgradable --configuration-matching='^releaseRuntimeClasspath$' --exclude=radar-android-empatica
